# -*- coding: utf-8 -*-
"""datacleaning

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e62lpEBMOEBlx-egAALiPjHkLC2dBZpX
"""

import pandas as pd
import numpy as np

df = pd.read_csv("DatasetforDataAnalytics.csv")

print("shape:", df.shape)
print(df.info())
print(df.head())

print("\nMissing values pr column:")
print(df.isnull().sum())

df = df.dropna(thresh=len(df.columns) * 0.5)

for col in df.columns:
  if df[col].dtype in ['int64', 'float64']:
      df[col] = df[col].fillna(df[col].median())
  else:
       df[col] = df[col].fillna(df[col].mode()[0])

df = df.drop_duplicates()

for col in df.select_dtypes(include='object').columns:
   df[col] = df[col].str.strip().str.lower()

for col in df.select_dtypes(include=['int64', 'float64']).columns:
  Q1 = df[col].quantile(0.25)
  Q3 = df[col].quantile(0.75)
  IQR = Q3-Q1
  lower_limit = Q1 - 1.5*IQR
  upper_limit = Q3 + 1.5*IQR
  df = df[(df[col] >= lower_limit) & (df[col] <= upper_limit)]

df = df.reset_index(drop=True)

df.to_csv("DatasetforDataAnalytics_cleaned.csv", index=False)
print("\nCleaned dataset saved as DatasetforDataAnalytics_cleaned.csv")
print("New shape:", df.shape)

